# -*- coding: utf-8 -*-
"""simulador_de_mensalidade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XRX9TO2wrztVAYd1k8gFqiL97vYBNhb_
"""

# Aula pratica EBAC - SIMULADOR DE MENSALIDADE

while True: # o while true vai nos permitir fazer varias simulações sem ficar dando play no programa de novo
  print("CALCULADORA DE ASSINATURAS")

  # Vamos atribuir a variavel o valor que o usuario digitar, pra isso vamos usar o input, mas como é um valor e as vezes é quebrado vamos converter usando o float para criar numeros quebrados
  valor_mensal = float(input("Digite o valor da mensalidade (ex: 29.90):"))

  # Nessa variavel vamos usar a mesma estrutura mas dessa vez, como são meses, vamos vamos usar o int para numeros inteiros
  qtd_meses = int(input("Digite a duração so contrato em meses(Sómente numeros):"))

  # Agora tem as multiplicações, vou usar multiplicação, divisão, adição e subtração para trazer informaçoes mais completas sobre as mensalidades

  valor_total = valor_mensal * qtd_meses
  custo_diario = valor_mensal / 30
  total_com_taxa = valor_total + 9.90
  total_com_desconto = valor_total - 5.50


  # Agora vamos pro resultado!!
  print("------------------------------")
  print("RELATÓRIO FINANCEIRO")
  print(f"Valor total: R$ {valor_total:.2f}")
  print(f"Custo por dia: R$ {custo_diario:.2f}")
  print(f"Total com taxa(+9.90): R$ {total_com_taxa:.2f}")
  print(f"Total com desconto(-5.50): R$ {total_com_desconto:.2f}")

  # Agora vamos usar a condicional para dar um feedback sobre a duração do contato em forma de dicas
  if qtd_meses >= 12:
    print("==>Contrato longo, elegivel a desconto de 5.50 e isenção de taxa<==")
  else:
    print("==>Contrato curto, para desconto e isenção de taxa, atualize para o contrato anual<==")

  # Vamos verificar se o usuario quer fazer outra simulação ou parar o app
  continuar = input("Deseja fazer outra simulação? (s/n)")
  if continuar != 's':
    print("Encerrando o sistema...")
    break

